# .github/workflows/main.yml

# 工作流的名称
name: 尚香书苑自动签到

# 触发工作流的事件
on:
  # 允许你手动在 Actions 页面触发这个工作流
  workflow_dispatch:

  # 定时任务
  schedule:
    # Cron 表达式，表示在每天的 UTC 时间 0点0分 运行
    # UTC 0点 对应北京时间早上8点
    - cron: '0 0 * * *'

# 定义工作流中的一个或多个作业
jobs:
  check-in-job:
    # 作业运行的虚拟机环境
    runs-on: ubuntu-latest

    # 作业中的步骤
    steps:
      # 第一步：检出你的代码
      - name: 检出代码
        uses: actions/checkout@v3

      # 第二步：设置 Python 环境
      - name: 设置 Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 第三步：安装依赖
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 第四步：运行签到脚本
      - name: 执行签到脚本
        env:
          # 将你在 GitHub Secrets 中设置的值，注入到环境变量中
          # 请确保你已经在仓库的 Settings -> Secrets and variables -> Actions 中设置了这些秘密
          sxsy: ${{ secrets.SXSY }}
          DDDD_OCR_URL: ${{ secrets.DDDD_OCR_URL }}
        run: python 尚香书苑.py
